"""Initial migration with MySQL optimization

Revision ID: 3d3aaad3b08a
Revises: 
Create Date: 2025-07-10 14:36:36.646950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d3aaad3b08a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_methods', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_api_methods_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_methods_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_methods_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_methods_status'), ['status'], unique=False)

    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.alter_column('base_url',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.alter_column('base_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('api_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_methods_status'))
        batch_op.drop_index(batch_op.f('ix_api_methods_method'))
        batch_op.drop_index(batch_op.f('ix_api_methods_folder_id'))
        batch_op.drop_index(batch_op.f('ix_api_methods_created_by'))
        batch_op.alter_column('url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
